//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.PrestacionesLaborales = new HashSet<PrestacionesLaborale>();
            this.Nominas = new HashSet<Nomina>();
        }
    
        public int EmpleadoID { get; set; }
        public string NombreEmpleado { get; set; }
        public int DepartamentoID { get; set; }
        public int CargoID { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public decimal Salario { get; set; }
        public bool Estado { get; set; }
        public Nullable<decimal> AFP { get; set; }
        public Nullable<decimal> ARS { get; set; }
        public Nullable<decimal> ISR { get; set; }
        public Nullable<decimal> SalarioNeto { get; set; }
        public string TiempoLaborado { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrestacionesLaborale> PrestacionesLaborales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nomina> Nominas { get; set; }
    }
}
