//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int NominaID { get; set; }
        public int EmpleadoID { get; set; }
        public System.DateTime FechaNomina { get; set; }
        public decimal SalarioBase { get; set; }
        public decimal AFP { get; set; }
        public decimal ARS { get; set; }
        public decimal ISR { get; set; }
        public Nullable<decimal> SalarioNeto { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
